name = "Julies Essentials"
author = "Julie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcad207cdacb879e9e0719eeb4f036a21581f179ff47644ac4de4534b688dfcf"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.10"
